### PR TITLE
Remove `get_key_value` to enable building in stable rust.

### LINKED ISSUE #4: make rust-agent not depends in nightly feature

### PR DESCRIPTION
**Pull request by ericho**
The `get_key_value` method is currently only avaiable in nightly rust.
As only this feature is required it worth to refactor and enable building
in the stable channel.

The method was removed by first getting the value from the CGROUPS hashmap,
then key is get by iterating over all the keys. The checks for an empty key and
key == "devices" were moved out of the hashmap block.

The README.md was updated as well to detail the instructions for stable rust.

Fixes #4

### CODE REVIEW

**Comment by ericho** [comment]
Tested with: `rustc 1.38.0 (625451e37 2019-09-23)`

**Comment by yyyeerbo** [comment]
> We might need to remove install_rust.sh from .travis.yml ifi rustfmt is installed by default. Otherwise, we have to patch .ci/install_rust.sh to install rustfmt in kata-containers/tests repository.
> 
> We have some basic checks to see if rust agent builds and the tests runs.
> 
> ERROR: found HTTP error status codes for URL https://github.com/kata-containers/kata-agent
> ERROR: Invalid URL 'https://github.com/kata-containers/kata-agent' found in the following files:
> README.md
> 
> Could you please help modify https://github.com/kata-containers/kata-agent to https://github.com/kata-contianers/kata-containers to make ci happy?
> 
> This feature will be stable in 1.40, as I know about. I am not sure if we have to patch the code. Maybe just switch to stable rust release after 1.40? @lifupan @jodh-intel
> 
> rust agent will be landed into kata-containers soon, I might have to merge this patch into the new repository..

I sent patch to use version from versions.yaml. I think this patch is good once README.md is patched to make ci happy

**Comment by jodh-intel** [comment]
lgtm, but now https://github.com/kata-containers/kata-containers/pull/57 has landed, please could you raise a PR on https://github.com/kata-containers/kata-containers instead?

**Comment by ericho** [comment]
@jodh-intel sure, I'll send this PR to that repository.

**Pull request closed without merging**
